[tool.poetry]
name = "sample-for-mpi4py"
version = "0.1.0"
description = ""
authors = ["hyukychang <seunghyuk.dev@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
mpi4py = "4.0.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
